adding priority class
jainishshah17/tugger pull request #170
Opened 2023-05-16 19:41 UTC by Jennls82

adding a priority class config to the chart and corresponding docs

### Checklist
- [x] Chart version bumped

2023-05-16 19:54 UTC, kd7lxl requested changes
`priorityClassName` change LGTM.

2023-05-16 19:54 UTC, kd7lxl commented on chart/tugger/README.md
> +Autogenerated from chart metadata using [helm-docs v1.11.0](https://github.com/norwoodj/helm-docs/releases/v1.11.0)
I'm not in favor of committing generated code without some automation to generate it. It's just going to become stale upon the next change. This type of change belongs in its own PR where the merits can be discussed without blocking your other change.

2023-05-16 20:08 UTC, Jennls82 commented on chart/tugger/README.md
> +Autogenerated from chart metadata using [helm-docs v1.11.0](https://github.com/norwoodj/helm-docs/releases/v1.11.0)
sgtm removed in next commit

2023-05-16 20:15 UTC, kd7lxl approved these changes

2023-05-17 03:02 UTC, jainishshah17 approved these changes
LGTM

2023-05-17 03:02 UTC, merged