Regex-based mutation policy
jainishshah17/tugger pull request #19
Opened 2020-12-15 00:05 UTC by kd7lxl

I've implemented the policy interpreter for the spec defined in https://github.com/infobloxopen/tugger/issues/10.

Take a look at c92b714 and let me know if you have any initial comments.

TODO: integrate the policy engine with `main()`.

2020-12-15 02:17 UTC, jainishshah17 commented
@kd7lxl We should bump minor version of Tugger as there is major change in functionality.

2020-12-15 16:52 UTC, kd7lxl commented
> @kd7lxl We should bump minor version of Tugger as there is major change in functionality.

Should it be a major version since the config will be backwards-incompatible?

2020-12-15 17:10 UTC, jainishshah17 commented
> > @kd7lxl We should bump minor version of Tugger as there is major change in functionality.
> 
> Should it be a major version since the config will be backwards-incompatible? e.g., 1.0.0.

As current version is `0.0.7` I was thinking to bump minor version. e.g `0.1.0`
What do you think?

2020-12-15 19:18 UTC, kd7lxl commented
Initially I was thinking that if this new configuration scheme breaks the existing config, it should be a major version bump, `1.0.0`. Now I'm halfway through implementing it and I think I can conditionally ignore the existing config iff the user defines a new config file / rules. With no breaking changes, I think `0.1.0` is good.

2020-12-16 16:36 UTC, jainishshah17 commented on cmd/tugger/main.go
> +			log.Println("Changing image from", originalImage, "to", container.Image)
I think you missed `sendSlackNotification()` here. Can you please add it.

2020-12-16 16:37 UTC, tgjonestx requested changes

2020-12-16 16:37 UTC, tgjonestx commented on cmd/tugger/main.go
> +		log.WithError(err).WithField("body", string(data)).Error("could not parse request")
Message should be "could not read request" to distinguish this error from the one at line 301.

Also, I'm not familiar with the payload contents, but if there is a chance that `data` could contain sensitive information then it shouldn't be logged.

2020-12-16 16:37 UTC, tgjonestx commented on cmd/tugger/main.go
> +			log.WithError(err).Error("got error from Slack")
To distinguish from line 422, the message should be say something different like "unable to construct request for Slack"

2020-12-16 16:37 UTC, tgjonestx commented on cmd/tugger/main.go
> +			log.Fatal(err)
I think this message needs some more context. Looking at some of the failure modes in Policy.Load(), a user with malformed policy might be a little perplexed because the raw GO error from the json or regexp libraries will be output here. So maybe something like `log.Fatalf("Unable to read policy file %s: %s", *policyFile, err)`

2020-12-16 16:37 UTC, tgjonestx commented on cmd/tugger/main.go
> +			log.Println("Changing image from", originalImage, "to", container.Image)
Nit - missing leading/trailing spaces around the image names

2020-12-16 16:37 UTC, tgjonestx commented on cmd/tugger/main.go
> +		if policy != nil {
I think there's an edge case for a policy file without rules in which case the existing logic in ValidateImage will return false for every input. 
```suggestion
		if policy != nil  && len(policy.Rules) > 0 {
```

2020-12-16 16:37 UTC, tgjonestx commented on cmd/tugger/policy.go
> +				msg = fmt.Sprintf("%s does not exist in private registry", image)
To provide more context in debugging, it would be helpful to know the container name like the message [here in main.go](https://github.com/jainishshah17/tugger/blob/57e85b0e4c70bf2d554961966b3df7775885da7f/cmd/tugger/main.go#L273)

2020-12-16 16:37 UTC, tgjonestx commented on cmd/tugger/policy_test.go
> +		},
For completeness, `defaultPolicy` and this test case should validate the `Always` condition.

2020-12-16 17:14 UTC, kd7lxl commented on cmd/tugger/main.go
> +			log.Println("Changing image from", originalImage, "to", container.Image)
It's over here now, which I think is the same logic as before: https://github.com/jainishshah17/tugger/blob/57e85b0e4c70bf2d554961966b3df7775885da7f/cmd/tugger/policy.go#L68
The logic is to only send the slack message when the rewrite fails. It doesn't send for routine rewrites. This is the logic I want -- if you want a slack message for every rewrite, I can add a config option to control that. What do you think?

2020-12-16 17:16 UTC, kd7lxl commented on cmd/tugger/main.go
> +		log.WithError(err).WithField("body", string(data)).Error("could not parse request")
`data` mostly contains the pod spec. It would be against best practice for a pod spec to contain any sensitive information, so I think it's safe to assume we can log it.

2020-12-16 17:20 UTC, kd7lxl commented on cmd/tugger/main.go
> +			log.Fatal(err)
Here's a demo with the current code:
```
% go run . --policy-file ../../images.list 
WARNING: Package "github.com/golang/protobuf/protoc-gen-go/generator" is deprecated.
        A future release of golang/protobuf will delete this package,
        which has long been excluded from the compatibility promise.

{"level":"fatal","msg":"yaml: unmarshal errors:\n  line 1: cannot unmarshal !!str `one two...` into main.Policy","time":"2020-12-16T09:18:16.205852-08:00"}
exit status 1
```

2020-12-16 17:23 UTC, kd7lxl commented on cmd/tugger/main.go
> +			log.Println("Changing image from", originalImage, "to", container.Image)
`Println` is used to automatically add the spaces between arguments: https://golang.org/pkg/fmt/#Println

2020-12-16 17:29 UTC, kd7lxl commented on cmd/tugger/main.go
> +		if policy != nil {
The helm chart implementation currently protects against this configuration, but it's reasonable to assume it could be deployed without helm...

If we want to consider a policy with no rules as invalid, I think this logic should go in `Load()`, where it validates the config, not here in the webhook handler.

However, I'm not convinced that a policy with no rules is invalid. It would be a clever way to block pod creation in a cluster for a bit, if you had a need to do that. Maybe `Load()` should just log a warning if there are no rules, since it's likely a misconfiguration.

2020-12-16 17:32 UTC, kd7lxl commented on cmd/tugger/policy.go
> +				msg = fmt.Sprintf("%s does not exist in private registry", image)
Unfortunately the container name is not available in this scope. I'd hate to complicate the return values more, but that's one way I could think of to bubble this message back up to a scope that has the container name and could log from there.

2020-12-16 17:49 UTC, kd7lxl commented on cmd/tugger/policy_test.go
> +		},
Added a test case for `Always` in b9e3387

2020-12-16 18:03 UTC, kd7lxl commented on cmd/tugger/main.go
> +		log.WithError(err).WithField("body", string(data)).Error("could not parse request")
Updated in a521570

2020-12-16 18:04 UTC, kd7lxl commented on cmd/tugger/main.go
> +			log.WithError(err).Error("got error from Slack")
These changes were approved in https://github.com/infobloxopen/tugger/pull/9 and are now just merging upstream, but I can change them regardless... Changed in a521570

2020-12-16 18:04 UTC, kd7lxl commented on cmd/tugger/main.go
> +			log.Fatal(err)
Here's a demo after a521570:
```
% go run . --policy-file ../../images.list         
WARNING: Package "github.com/golang/protobuf/protoc-gen-go/generator" is deprecated.
        A future release of golang/protobuf will delete this package,
        which has long been excluded from the compatibility promise.

{"error":"yaml: unmarshal errors:\n  line 1: cannot unmarshal !!str `one two...` into main.Policy","level":"fatal","msg":"failed to load policy file","policy-file":"../../images.list","time":"2020-12-16T10:00:45.791407-08:00"}
exit status 1
```

2020-12-16 18:14 UTC, kd7lxl commented on cmd/tugger/main.go
> +		if policy != nil {
Added validation to `Load()` in 85bb981.

2020-12-16 18:28 UTC, tgjonestx approved these changes

2020-12-16 21:41 UTC, jainishshah17 commented on cmd/tugger/main.go
> +			log.Println("Changing image from", originalImage, "to", container.Image)
Initially I added it to send notification on every rewrite. So that users can have up to date info without having to look at Tugger logs. If you think that is too much noise than we can go your way.

2020-12-16 21:51 UTC, kd7lxl commented on cmd/tugger/main.go
> +			log.Println("Changing image from", originalImage, "to", container.Image)
For some more context, I changed the logic back here: https://github.com/infobloxopen/tugger/pull/9/commits/de4b39eb2d0f4a87d6cd394bb18240f34f116262 which didn't get pushed upstream until this PR.

2020-12-16 22:06 UTC, jainishshah17 commented
@kd7lxl Let me know when you are ready to merge this PR.

2020-12-16 22:07 UTC, jainishshah17 approved these changes

2020-12-16 23:46 UTC, kd7lxl commented
> @kd7lxl Let me know when you are ready to merge this PR.

You can merge whenever.

2020-12-17 03:03 UTC, merged